theme = "catppuccin_frappe"

[editor]
line-number = "relative"
cursorline = true
color-modes = true
end-of-line-diagnostics = "hint"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true

[editor.inline-diagnostics]
cursor-line = "error"

[keys.normal]
"C-f" = ":format"
"C-w" = ":write"
"C-n" = ":buffer-previous"
"C-m" = ":buffer-next"
"C-q" = ":q"
"S-q" = ":wq"
"C-d" = "kill_to_line_end"
"C-h" = "jump_view_left"
"C-l" = "jump_view_right"
"C-j" = "jump_view_down"
"C-k" = "jump_view_up"
"C-e" = ":vsplit-new"
"C-r" = ":hsplit-new"
"S-y" = ":primary-clipboard-yank"
"C-p" = ":primary-clipboard-paste-after"
"A-j" = ["extend_to_line_bounds", "delete_selection", "paste_after"]
"A-k" = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]
