theme = "nord-night"

[editor]
true-color = true
line-number = "relative"
cursorline = true
color-modes = true
rulers = [80]
bufferline = "always"
end-of-line-diagnostics = "hint"
shell = ["zsh", "-c"]
mouse = false

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true

[editor.inline-diagnostics]
cursor-line = "error"

[editor.file-picker]
hidden = false

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
tab = ":buffer-previous"
"A-f" = ":format"
"C-w" = ":write"
"S-tab" = ":buffer-next"
"C-q" = ":q"
"S-q" = ":wq"
"C-d" = "kill_to_line_end"
"C-h" = "jump_view_left"
"C-l" = "jump_view_right"
"C-j" = "jump_view_down"
"C-k" = "jump_view_up"
"C-e" = ":vsplit-new"
"C-r" = ":hsplit-new"
"S-k" = "hover"
"A-r" = ":config-reload"
"A-j" = ["extend_to_line_bounds", "delete_selection", "paste_after"]
"A-k" = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]
"A-x" = ":buffer-close"
"A-[" = "hsplit"
"A-]" = "vsplit"
"A-c" = "wclose"
